---
registry_conf_dir: "/etc/containers/registries.conf.d"
quay_image_repo: "quay.io"
ceph_version: "v19.2.2"
ceph_conf_dir: "/etc/ceph"
ceph_ssh_config: "{{ ceph_conf_dir }}/ssh_config"
ceph_bootstrap_templates:
  - {src: "999-local-registry.conf.j2", dest: "{{ registry_conf_dir }}/999-local-registry.conf"}
  - {src: "{{ ceph_ssh_config|basename }}.j2", dest: "{{ ceph_ssh_config }}"}
ceph_artifacts_dir: "{{ ansible_env.HOME }}/ceph-artifacts"
ceph_bootstrap_params: "{{ single_osd_node | ternary('--single-host-defaults', '') }}"
ceph_health_ok: "HEALTH_OK"
ceph_health_retries: 18
ceph_health_delay: 10
# haproxy
haproxy_conf_dir: "/etc/haproxy"
service_conf:
  - {dest: "{{ haproxy_conf_dir }}/conf.d/ceph.cfg", owner: "root", group: "haproxy", mode: "0640"}
balance: roundrobin
inter: 2s
rise: 2
fall: 3
...
