---
- name: confirm whether user really meant to purge the cluster
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to purge the ceph cluster (No | Yes, I really mean it)?
      private: false
  tasks:
    - name: exit playbook, if user did not mean to purge the cluster
      fail:
        msg: >
          "Exiting the playbook, the ceph cluster was NOT purged.
           To purge the cluster, enter 'Yes, I really mean it' on the prompt.
      when: ireallymeanit != 'Yes, I really mean it'

- name: Purge ceph cluster
  hosts: ceph
  any_errors_fatal: true
  tasks:
    - name: purge ceph cluster
      tags:
        - ceph_purge
      include_role:
        name: burrito.ceph
        tasks_from: purge
...
