---
- name: deploy descheduler
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: burrito.descheduler
      when: (groups['kube_control_plane']|length) > 1
      tags: ['descheduler', 'burrito']
...
