---
- name: check installation type (online/offline)
  hosts: localhost
  gather_facts: false
  tasks:
    - name: exit playbook if installation type is online
      fail:
        msg: >-
          Exiting the playbook since you are installing burrito online.
          This playbook is only for offline installation.
      when: not offline

- name: deploy genesis registry and local repository
  hosts: kube_control_plane
  any_errors_fatal: true
  roles:
    - role: burrito.genesisregistry
      when: offline
      tags: ['genesisregistry', 'burrito']

- name: deploy local yum repository
  hosts: all
  any_errors_fatal: true
  roles:
    - role: burrito.localrepo
      when: offline
      tags: ['localrepo', 'burrito']
...
