---
- name: deploy genesis registry and local repository
  hosts: kube_control_plane
  any_errors_fatal: true
  roles:
    - role: burrito.genesisregistry
      when: offline
      tags: ['genesisregistry', 'burrito']

- name: deploy local yum repository
  hosts: all
  any_errors_fatal: true
  roles:
    - role: burrito.localrepo
      when: offline
      tags: ['localrepo', 'burrito']

- name: deploy Graceful Node Shutdown Helper (GNSH)
  hosts: k8s_cluster
  any_errors_fatal: true
  roles:
    - role: burrito.gnsh
      tags: ['gnsh', 'burrito']
...
