---
- name: Deploy ceph-csi playbook
  any_errors_fatal: true
  ansible.builtin.import_playbook: ceph-csi.yml
  tags: ceph-csi

- name: deploy descheduler
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: burrito.descheduler
      when: (groups['kube_control_plane']|length) > 1
      tags: ['descheduler', 'burrito']

- name: deploy Asklepios auto-healing service
  hosts: localhost
  any_errors_fatal: true
  roles:
    - role: burrito.asklepios
      when: groups['kube_control_plane']|length > 1
      tags: ['asklepios', 'burrito']

- name: Deploy k8s patch playbook
  any_errors_fatal: true
  ansible.builtin.import_playbook: k8spatch.yml
  tags: k8spatch
...
