---
- name: powerflex pfmp playbook
  hosts: mdm[0]:pfmp:pfmp_node
  any_errors_fatal: true
  tasks:

    - name: get mgmt network segment
      ansible.builtin.set_fact:
        pfmp_mgmt_net_segment: "{{ hostvars[ groups['mdm'][0] ][ 'ansible_' + hostvars[ groups['mdm'][0] ].mgmt_iface_name].ipv4.network|ansible.builtin.regex_replace('^(.*)\\.\\d+$', '\\1') }}"
    - name: get storage network segment
      ansible.builtin.set_fact:
        pfmp_storage_net_segment: "{{ hostvars[ groups['mdm'][0] ][ 'ansible_' + hostvars[ groups['mdm'][0] ].storage_iface_name].ipv4.network|ansible.builtin.regex_replace('^(.*)\\.\\d+$', '\\1') }}"
    - name: get the management netmask prefix
      ansible.builtin.set_fact:
        pfmp_mgmt_net_prefix: "{{ hostvars[ groups['mdm'][0] ][ 'ansible_' + hostvars[ groups['mdm'][0] ].mgmt_iface_name].ipv4.prefix }}"
    - name: get the storage netmask prefix
      ansible.builtin.set_fact:
        pfmp_storage_net_prefix: "{{ hostvars[ groups['mdm'][0] ][ 'ansible_' + hostvars[ groups['mdm'][0] ].storage_iface_name].ipv4.prefix }}"

    - name: deploy PowerFlex Management Platform on a single node
      include_role:
        name: burrito.powerflex
        tasks_from: pfmp
      when:
        - '"powerflex" in storage_backends'
        - inventory_hostname in groups['pfmp']
      tags: ['powerflex', 'pfmp']

    - name: deploy PowerFlex Management Platform on already-prepared nodes
      include_role:
        name: burrito.powerflex
        tasks_from: pfmp_node
      when:
        - '"powerflex" in storage_backends'
        - inventory_hostname in groups['pfmp_node']
      tags: ['powerflex', 'pfmp_node']
...
