---
- name: deploy powerflex csi
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: deploy powerflex csi
      include_role:
        name: burrito.powerflex
        tasks_from: csi
      when: '"powerflex" in storage_backends'
      tags: ['powerflex']
...
