---
- name: check installation type (online/offline)
  hosts: localhost
  gather_facts: false
  tasks:
    - name: exit playbook if installation type is online
      fail:
        msg: >-
          Exiting the playbook since you are installing burrito online.
          This playbook is only for offline installation.
      when: not offline

- name: Pull, tag and push images to local registry
  hosts: localhost
  gather_facts: true
  any_errors_fatal: true

  environment:
    LOCAL_REGISTRY: "{{ containerd_insecure_registries['local_registry'] }}"
    SEED_REGISTRY: "{{ containerd_insecure_registries['seed_registry'] }}"
    OFFLINE: "{{ offline | ternary(true, false) }}"
    INCLUDE_NETAPP: "{{ ('netapp' in storage_backends)|ternary(true, false) }}"
    INCLUDE_PFX: "{{ ('powerflex' in storage_backends)|ternary(true, false) }}"

  tasks:
    - name: Registry | get registry pod name
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ registry_namespace }}"
        label_selectors:
          - "k8s-app=registry"
      register: registry_pod
      when: offline
      become: true
    - name: Registry | copy registry image into the registry pod (offline)
      ansible.builtin.command: >-
        kubectl -n {{ registry_namespace }} \
          cp /mnt/registry/docker \
          {{ registry_pod.resources[0].metadata.name }}:/var/lib/registry/
      register: _copy_result
      until: _copy_result.rc == 0
      retries: 3
      delay: 3
      become: true
      when: offline
    - name: Registry | run registry.sh script (online)
      ansible.builtin.shell: ./registry.sh &> /tmp/registry_play.log
      args:
        chdir: "{{ playbook_dir }}/scripts"
      become: true
      when: not offline
...
