---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asklepios-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asklepios-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asklepios-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: asklepios-cluster-role
subjects:
  - name: asklepios-sa
    kind: ServiceAccount
    namespace: kube-system
