---
- name: Update server field in component kubeconfigs
  lineinfile:
    dest: "{{ kube_config_dir }}/{{ item }}"
    regexp: '^    server: https'
    line: '    server: {{ kube_apiserver_endpoint }}'
    backup: true
  with_items:
    - admin.conf
    - controller-manager.conf
    - kubelet.conf
    - scheduler.conf
  notify:
    - "Control plane | Restart kube-controller-manager"
    - "Control plane | Restart kube-scheduler"
    - "Control plane | reload kubelet"

- name: Update etcd-servers for apiserver
  ansible.builtin.replace:
    path: "{{ kube_config_dir }}/manifests/kube-apiserver.yaml"
    regexp: '(etcd-servers=).*'
    replace: '\1{{ etcd_access_addresses }}'
  when: etcd_deployment_type != "kubeadm"
