---
artifacts_dir: "{{ ansible_env.HOME }}/purestorage-artifacts"

service_conf:
  - {dest: "/etc/multipath.conf", owner: "root", group: "root", mode: "0600"}
systemd_service_name:
  - multipathd.service

template_files:
  - {dest: "{{ artifacts_dir }}/pure.json"}
  - {dest: "{{ artifacts_dir }}/versions.yaml"}
  - {dest: "{{ artifacts_dir }}/portworx_operator.yml"}
  - {dest: "{{ artifacts_dir }}/portworx_storagecluster.yml"}
  - {dest: "{{ artifacts_dir }}/portworx_storageclass.yml"}

purestorage_mgmt_ip: ~
purestorage_api_token: ~

purestorage_namespace: "portworx"

uninstall_files:
  - {dest: "{{ artifacts_dir }}/portworx_storageclass.yml"}
  - {dest: "{{ artifacts_dir }}/portworx_storagecluster.yml"}
  - {dest: "{{ artifacts_dir }}/portworx_operator.yml"}
...
