---
- name: HAProxy | templating RadosGW haproxy config
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "templates/{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_conf }}"
  become: true
  notify:
    - haproxy reload service
  when: inventory_hostname in groups['kube_control_plane']
...
