---
- name: Rocky Linux | Import a ceph repo key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ ceph_repo_key_url }}"
  become: true
  when: not offline

- name: Rocky Linux | Install online packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  loop: "{{ online_pkgs }}"
  become: true
  when: not offline

- name: Rocky Linux | Template ceph.repo
  ansible.builtin.template:
    dest: "/etc/yum.repos.d/ceph.repo"
    src: "templates/ceph.repo.j2"
  become: true
  when: not offline

- name: Rocky Linux | Install prerequisite packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  loop: "{{ prereq_pkgs }}"
  become: true

- name: Rocky Linux | Install packages on ceph servers
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ packages }}"
  when: inventory_hostname in groups['ceph_servers']

- name: Rocky Linux | Install packages on ceph clients
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ pkg_state }}"
  register: _pkg
  until: not _pkg.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ client_pkgs }}"
  when: inventory_hostname in groups['clients']
...
