---
- name: Setup | create ceph artifacts directory
  ansible.builtin.file:
    path: "{{ ceph_artifacts_dir }}"
    state: directory
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: true

- name: Setup | create ceph cluster service spec file
  ansible.builtin.template:
    dest: "{{ ceph_artifacts_dir }}/cluster.yml"
    src: "cluster.yml.j2"
    mode: "0644"
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: true
  
- name: Setup | set up the ceph cluster
  ansible.builtin.shell: >-
    ceph orch apply -i {{ ceph_artifacts_dir }}/cluster.yml
  become: true
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: true

- name: Setup | wait until ceph cluster is healthy
  ansible.builtin.command: ceph health
  become: true
  register: ceph_health
  until: ceph_health.stdout == "HEALTH_OK"
  retries: 15
  delay: 20
  delegate_to: "{{ groups['mons'][0] }}"
  run_once: true
...
