galaxy_info:
  namespace: burrito
  role_name: descheduler
  author: "Heechul Kim <jijisa@iorchard.net>"
  description: Ansible role to run descheduler for kubernetes
  company: iOrchard, Inc.
  license: Apache-2.0
  min_ansible_version: "2.15"
  platforms:
    - name: Rocky Linux
      versions:
        - 8.x
  galaxy_tags:
    - kubernetes

dependencies: []
