---
install_descheduler: false
artifacts_dir: "{{ ansible_env.HOME }}/descheduler-artifacts"
pod:
  replicas: 1

template_files:
  - {dest: "{{ artifacts_dir }}/deployment.yaml"}

# container image version
descheduler_version: "v0.32.1"
descheduler_interval: "3m"
descheduler_log_level: "3"
...
