---
artifacts_dir: "{{ ansible_env.HOME }}/asklepios-artifacts"
pod:
  replicas: 1

template_files:
  - {dest: "{{ artifacts_dir }}/configmap.yaml"}
  - {dest: "{{ artifacts_dir }}/deployment.yaml"}

manifest_files:
  - "{{ artifacts_dir }}/configmap.yaml"
  - "{{ artifacts_dir }}/rbac.yaml"
  - "{{ artifacts_dir }}/deployment.yaml"

asklepios:
  version: "0.2.0"
  verbose: false
  sleep: 10
  kickout: 60
  kickin: 60
  balancer: false
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 10
  terminationGracePeriodSeconds: 10
  tolerationSeconds: 20
...
