---
- name: Cluster | create a single-node cluster on the primary MDM
  ansible.builtin.command: >-
    scli --create_mdm_cluster \
      --primary_mdm_name {{ groups['mdm'][0] }} \
      --primary_mdm_ip {% for siface in storage_iface_names %}{{ hostvars[groups['mdm'][0]]['ansible_'+siface].ipv4.address }}{% if not loop.last %},{% endif %}{% endfor %}
      --primary_mdm_management_ip {{ hostvars[groups['mdm'][0]]['ansible_'+mgmt_iface_name].ipv4.address }} \
      --cluster_virtual_ip {{ mdm_ip|join(',') }} \
      --primary_mdm_virtual_ip_interface {{ storage_iface_names|join(',') }} \
      --accept_license \
      --approve_certificate
  register: res
  delegate_to: "{{ groups['mdm'][0] }}"
  run_once: true
  failed_when: res.rc not in [0, 7]
  changed_when: res.rc == 0

- name: Cluster | add the secondary MDM to the MDM cluster
  ansible.builtin.shell: >-
    scli --login --p12_path {{ mdm_certs.client }} \
      --p12_password '{{ mdm_password }}' && \
    scli --add_standby_mdm \
      --new_mdm_name {{ groups['mdm'][1] }} \
      --mdm_role manager \
      --new_mdm_ip {% for siface in hostvars[groups['mdm'][1]]['storage_iface_names'] %}{{ hostvars[groups['mdm'][1]]['ansible_'+siface].ipv4.address }}{% if not loop.last %},{% endif %}{% endfor %} \
      --new_mdm_management_ip {{ hostvars[groups['mdm'][1]]['ansible_'+hostvars[groups['mdm'][1]].mgmt_iface_name].ipv4.address }} \
      --new_mdm_virtual_ip_interface {{ hostvars[groups['mdm'][1]]['storage_iface_names']|join(',') }}
  register: res
  delegate_to: "{{ groups['mdm'][0] }}"
  run_once: true
  failed_when: res.rc not in [0, 7]
  changed_when: res.rc == 0
  no_log: true

- name: Cluster | add a tiebreaker to the MDM cluster
  ansible.builtin.shell: >-
    scli --login --p12_path {{ mdm_certs.client }} \
      --p12_password '{{ mdm_password }}' && \
    scli --add_standby_mdm \
      --new_mdm_name {{ groups['mdm'][2] }} \
      --mdm_role tb \
      --new_mdm_ip {% for siface in hostvars[groups['mdm'][2]]['storage_iface_names'] %}{{ hostvars[groups['mdm'][2]]['ansible_'+siface].ipv4.address }}{% if not loop.last %},{% endif %}{% endfor %}
  register: res
  delegate_to: "{{ groups['mdm'][0] }}"
  run_once: true
  failed_when: res.rc not in [0, 7]
  changed_when: res.rc == 0
  no_log: true

- name: Cluster | switch to 3-node cluster mode
  ansible.builtin.shell: >-
    scli --login --p12_path {{ mdm_certs.client }} \
      --p12_password '{{ mdm_password }}' && \
    scli --switch_cluster_mode \
      --cluster_mode 3_node \
      --add_secondary_mdm_name {{ groups['mdm'][1] }} \
      --add_tb_name {{ groups['mdm'][2] }}
  register: res
  delegate_to: "{{ groups['mdm'][0] }}"
  run_once: true
  failed_when: res.rc not in [0, 7]
  changed_when: res.rc == 0
  no_log: true
...
