---
- name: Config | reconfigure lia conf.txt
  ansible.builtin.lineinfile:
    path: "{{ lia_conf_file }}"
    line: "lia_port={{ lia_port }}"
    state: present
  become: true
  when: inventory_hostname in groups['powerflex']
  notify:
    - systemctl restart lia service

- name: Config | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Config | create openstack directory in scaleio directory
  ansible.builtin.file:
    path: "{{ scaleio_dir }}/openstack"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Config | add openstack connector.conf
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family|lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "root"
    mode: "0644"
  become: true
  loop:
    - {dest: "{{ scaleio_dir }}/openstack/connector.conf"}
...
