---
- name: Install | create powerflex package directory
  ansible.builtin.file:
    path: "{{ pkg_base }}"
    state: directory
  when: inventory_hostname in groups['powerflex']

- name: Install | extract powerflex package tarball
  ansible.builtin.unarchive:
    src: "{{ pkg_tarball }}"
    dest: "{{ pkg_base }}"
  when: inventory_hostname in groups['powerflex']

- name: Install | install ActiveMQ
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.activemq }}
  become: true
  when: inventory_hostname in groups['powerflex']

- name: Install | install LIA
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.lia }}
  environment:
    TOKEN: "{{ lia_token }}"
  become: true
  when: inventory_hostname in groups['powerflex']

- name: Install | install SDS
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.sds }}
  become: true
  when: inventory_hostname in groups['sds']

- name: Install | install primary and secondary MDM
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.mdm }}
  environment:
    MDM_ROLE_IS_MANAGER: 1
  become: true
  when: inventory_hostname == groups['mdm'][0] or inventory_hostname == groups['mdm'][1]

- name: Install | install tiebreaker MDM
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.mdm }}
  environment:
    MDM_ROLE_IS_MANAGER: 0
  become: true
  when: inventory_hostname == groups['mdm'][2]

- name: Install | install SDC
  ansible.builtin.shell: >-
    dnf -y install {{ pkgs.sdc }}
  environment:
    MDM_IP: "{{ mdm_ip|join(',') }}"
  become: true
  when: inventory_hostname in groups['sdc']

- name: Install | clean up powerflex package directory
  ansible.builtin.file:
    path: "{{ pkg_base }}"
    state: absent
  when: inventory_hostname in groups['powerflex']
...
