{{/*
This manifest results a secret being created which has the key information
needed remote network for the Mariadb databases access.
*/}}

{{- if .Values.conf.db_acl.enabled }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-acl
type: Opaque
data:
  MYSQL_ACL_CIDR: {{ .Values.conf.db_acl.cidr | b64enc }}
{{- end }}
