---
- name: systemctl restart service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  loop: "{{ systemd_service_name }}"
...
