---
haproxy_confd: "{{ haproxy_conf_dir }}/conf.d"
files_conf:
  - {dest: "{{ haproxy_conf_dir }}/haproxy.cfg", owner: "root", group: "{{ service_name }}", mode: "0640"}
  - {dest: "/etc/default/haproxy", owner: "root", group: "root", mode: "0644"}
...
