---
- name: sshkey | create ssh key directory
  ansible.builtin.file:
    path: "{{ sshkey_dir }}"
    state: directory
    mode: "0700"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: true

- name: sshkey | create ssh keypairs on the first kube_control_plane
  community.crypto.openssh_keypair:
    path: "{{ sshkey_dir }}/id_rsa"
    state: present
    type: rsa
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: true

- name: sshkey | get ssh public key from the first node
  ansible.builtin.slurp:
    src: "{{ sshkey_dir }}/id_rsa.pub"
  register: ssh_public_key
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: true

- name: sshkey | add ssh public key as an authorized key to other nodes
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    manage_dir: true
    key: "{{ ssh_public_key.content | b64decode }}"
  when: inventory_hostname != groups['kube_control_plane'][0]
...
