---
- name: Setup | copy static script files
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "files/{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_script }}"
  become: true
  notify:
    - systemctl restart service

- name: Setup | set virtual router id
  ansible.builtin.set_fact:
    keepalived_vrid: "{{ 255 | random(start=1) }}"
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: true

- name: Setup | template keepalived configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "templates{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_conf }}"
  become: true
  notify:
    - systemctl restart service
...
