---
- name: Uninstall | uninstall worker node settings
  kubernetes.core.k8s:
    state: absent
    src: "{{ item }}"
  become: true
  delegate_to: localhost
  run_once: true
  loop: "{{ uninstall_files }}"

- name: Uninstall | Delete namespace
  kubernetes.core.k8s:
    state: absent
    name: "{{ primera_namespace }}"
    api_version: v1
    kind: Namespace
  become: true
  delegate_to: localhost
  run_once: true
...
