---
#- name: Genesis Registry | apply patch to hspc-csi-node daemonset
#  ansible.builtin.command: >-
#    kubectl patch ds hspc-csi-node -n {{ hitachi_namespace }} -p \
#      '{"spec": {"template": {"spec": {"containers": [{"name": "driver-registrar", "image": "{{ containerd_insecure_registries.genesis_registry }}/openshift4/ose-csi-node-driver-registrar:{{ osecsi_version }}"},{"name": "hspc-csi-driver", "image": "{{ containerd_insecure_registries.genesis_registry }}/hitachi/hspc-csi-driver:{{ hspc_csi_driver_version }}"}]}}}}'
#  become: true
#  delegate_to: localhost
#  run_once: true

- name: Genesis Registry | apply patch to hspc-csi-node daemonset
  kubernetes.core.k8s_json_patch:
    kind: DaemonSet
    namespace: "{{ hitachi_namespace }}"
    name: hspc-csi-node
    patch: "{{ hitachi_csi_daemonset_patch_list }}"
  become: true
  delegate_to: localhost
  run_once: true

- name: Genesis Registry | apply patch to hspc-csi-controller deployment
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    namespace: "{{ hitachi_namespace }}"
    name: hspc-csi-controller
    patch: "{{ hspc_csi_controller_deploy_patch_list }}"
  become: true
  delegate_to: localhost
  run_once: true

- name: Genesis Registry | apply patch to hspc-operator-controller-manager deployment
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    namespace: "{{ hitachi_namespace }}"
    name: hspc-operator-controller-manager
    patch: "{{ hspc_operator_deploy_patch_list }}"
  become: true
  delegate_to: localhost
  run_once: true
...
