---
- name: Genesis Registry | create registry root directory
  ansible.builtin.file:
    path: "{{ genesis_registry.root_dir }}"
    state: directory
  become: true

- name: Genesis Registry | copy registry binary to other controllers
  ansible.builtin.copy:
    dest: "/usr/bin/registry"
    src: "/usr/bin/registry"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  when: inventory_hostname != groups['kube_control_plane'][0]

- name: Genesis Registry | copy systemd service file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - {dest: "/etc/systemd/system/genesis_registry.service"}
  become: true

- name: Genesis Registry | templating template files
  ansible.builtin.template:
    dest: "{{ item }}"
    src: "{{ ansible_os_family | lower }}{{ item + '.j2' }}"
    mode: "0644"
  loop: 
    - "{{ genesis_registry.conf }}"
  become: true
  notify:
    - genesis registry restart service

- name: Genesis Registry | restart genesis registry service
  ansible.builtin.meta: flush_handlers

- name: Genesis Registry | check service is available
  ansible.builtin.uri:
    url: "http://{{ genesis_registry.addr }}"
    method: GET
    timeout: 3
  failed_when: false
  register: _result
  until: _result.status == 200
  retries: 5
  delay: 5

- name: Genesis Registry | pull images from seed registry
  ansible.builtin.shell: >-
    {{ image_pull_cmd }} \
      {{ containerd_insecure_registries.seed_registry }}/{{ item }}
  become: true
  delegate_to: localhost
  run_once: true
  loop: "{{ genesis_images }}"

- name: Genesis Registry | tag and push images to genesis registry
  ansible.builtin.include_tasks: "images.yml"
  loop: "[{% for h in groups['kube_control_plane'] %}'{{ hostvars[h].ip }}'{% if not loop.last %},{% endif %}{% endfor %}]"
  loop_control:
    loop_var: outer_item

- name: Genesis Registry | templating registry haproxy config
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ service_conf }}"
  become: true
  notify:
    - haproxy reload service

- name: Genesis Registry | take down offline services
  ansible.builtin.shell: >-
    ./offline_services.sh --down registry
  args:
    chdir: "{{ playbook_dir }}/scripts"
  become: true
  register: res
  failed_when: res.rc not in [0, 10]
  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  run_once: true

- name: Genesis Registry | apply patch to kubernetes static pods
  ansible.builtin.replace:
    path: "{{ k8s_manifest_dir }}/{{ item.name }}.yaml"
    regexp: "{{ containerd_insecure_registries.seed_registry }}"
    replace: "{{ containerd_insecure_registries.genesis_registry }}"
  become: true
  loop: "{{ k8s_services }}"
  notify:
    - kubelet restart service

- name: Genesis Registry | restart haproxy and kubelet service
  ansible.builtin.meta: flush_handlers

- name: Genesis Registry | pause before checking kubernetes services
  ansible.builtin.pause:
    seconds: 10

- name: Genesis Registry | wait until kubernetes services are running.
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - tier = control-plane
      - "component = {{ item.name }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 120
  register: _result
  become: true
  until: not _result.failed
  retries: 5
  delay: 5
  delegate_to: localhost
  run_once: true
  loop: "{{ k8s_services }}"

# cannot use kubernetes.core.k8s_json_patch 
# since kube-proxy needs to specify name in addition to image.
# So I use kubectl patch command.
- name: Genesis Registry | apply patch to kube-proxy daemonset
  ansible.builtin.command: >-
    kubectl patch ds kube-proxy -n kube-system -p \
      '{"spec": {"template": {"spec": {"containers": [{"name": "kube-proxy", "image": "{{ containerd_insecure_registries.genesis_registry }}/kube-proxy:{{ kube_version }}"}]}}}}'
  become: true
  delegate_to: localhost
  run_once: true

- name: Genesis Registry | apply patch to registry
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    namespace: "{{ registry_namespace }}"
    name: registry
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "{{ containerd_insecure_registries.genesis_registry }}/library/registry:{{ registry_version }}"
  become: true
  delegate_to: localhost
  run_once: true

- name: Genesis Registry | pause before going to addon patches
  ansible.builtin.pause:
    seconds: 10

- name: Genesis Registry | include patch tasks for calico
  ansible.builtin.include_tasks: "calico_patch.yml"

- name: Genesis Registry | include patch tasks for asklepios
  ansible.builtin.include_tasks: "asklepios_patch.yml"
  when: groups['kube_control_plane']|length > 1

- name: Genesis Registry | include patch tasks for ceph-csi
  ansible.builtin.include_tasks: "ceph_patch.yml"
  when: storage_backends[0] == 'ceph'

- name: Genesis Registry | include patch tasks for netapp
  ansible.builtin.include_tasks: "netapp_patch.yml"
  when: storage_backends[0] == 'netapp'

- name: Genesis Registry | include patch tasks for powerflex
  ansible.builtin.include_tasks: "powerflex_patch.yml"
  when: storage_backends[0] == 'powerflex'

- name: Genesis Registry | include patch tasks for hitachi
  ansible.builtin.include_tasks: "hitachi_patch.yml"
  when: storage_backends[0] == 'hitachi'

- name: Genesis Registry | include patch tasks for primera
  ansible.builtin.include_tasks: "primera_patch.yml"
  when: storage_backends[0] == 'primera

- name: Genesis Registry | include patch tasks for purestorage
  ansible.builtin.include_tasks: "purestorage_patch.yml"
  when: storage_backends[0] == 'purestorage'
...
